version: "3.8"

services:
  # --- 1. DATABASE SERVICE ---
  db_service:
    image: mysql:8.0
    container_name: db_C8
    restart: always
    environment:
      MYSQL_DATABASE: "rizqi"
      MYSQL_USER: "rizqizz"
      MYSQL_PASSWORD: "password12"
      MYSQL_ROOT_PASSWORD: "password123"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sikp_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- 2. BACKEND SERVICE ---
  app_service:
    build: ./backend
    container_name: app_C8
    restart: always
    expose:
      - "3000"
    environment:
      - DATABASE_URL=mysql://rizqizz:password12@db_service:3306/rizqi
      - JWT_SECRET=${JWT_SECRET:-rahasia_negara_oyako_123}
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      db_service:
        condition: service_healthy
    networks:
      - sikp_network
    volumes:
      - uploads_data:/app/uploads

  # --- 3. FRONTEND SERVICE ---
  frontend_service:
    build: ./frontend
    container_name: frontend_C8
    restart: always
    expose:
      - "5173"
    environment:
      - VITE_API_URL=
    depends_on:
      - app_service
    networks:
      - sikp_network

  # --- 3. NGINX SERVICE ---
  nginx_service:
    image: nginx:alpine
    container_name: nginx_C8
    restart: always
    ports:
      - "2583:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - uploads_data:/app/uploads:ro
    depends_on:
      - app_service
    # Network
    # volumes

#--- VOLUMES AND NETWORKS ---
# tambahkan bagian volumes dan networks di sini